### ISSUE TITLE
stuck when remove then append label view in container in win10

### ISSUE THREAD

**Issue by zaaack** [yue/yue#88] opened 2019-07-18 09:37 UTC

**Comment by zcbenz** [comment] 2020-05-10 13:11
Can you give an example?

**Comment by zaaack** [comment] 2020-05-11 05:58
This issue is a little old, the original use case that I trigge this issue worked around after adding setTimeout: https://gitee.com/zane_young/site-cloner/blob/master/src/react-libyue/renderer.ts#L52 . Comment setTimeout and run this program via `yarn start` might reproduce this issue. I'll try create a mininal app later.

**Comment by zcbenz** [comment] 2021-08-28 04:19
I'm closing this issue since there is no way to reproduce it.

**Closed by zcbenz** 2021-08-28 04:19 UTC
Labels: bug, needs-more-information
