### ISSUE TITLE
Label component does not works as expected

### ISSUE THREAD

**Issue by dimitrov-adrian** [yue/yue#84] opened 2019-05-10 14:52 UTC
There is some issue with the label component.
1. The alignment is seems to not be "start" as pointed in https://libyue.com/docs/latest/js/api/textattributes.html, but may be center
2. The wrap does not work in next example, but if change the label to "Lorem\nIpsum is ..." (adding new line in some place) then it works

Example code:
```javascript

const main = () => {
  console.log('main window')
  this.window = gui.Window.create({})
  this.window.setContentSize({ width: 280, height: 300 })
  this.window.setTitle(`Some window`)
  this.window.setAlwaysOnTop(true)
  const contentView = gui.Container.create()

  const appNameElement = gui.Label.create('Some title')

  const messageElement = gui.Label.create('Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.')
  let defaultFont = gui.Font.default()
  messageElement.setFont(gui.Font.create(defaultFont.getName(), defaultFont.getSize() * 0.86, defaultFont.getWeight(), defaultFont.getStyle()))
  messageElement.setStyle({
    padding: 5,
    wrap: true,
    ellipsis: true,
    height: 80
  })

  contentView.addChildView(appNameElement)
  contentView.addChildView(messageElement)
  this.window.setContentView(contentView)

  this.window.setVisible(true)
  this.window.activate()
}

```

**Comment by BorgLee** [comment] 2019-07-01 12:16
Try the 0.6.3 version.

**Comment by dimitrov-adrian** [comment] 2019-07-08 10:25
@BorgLee it doesn't works with 0.6.3

**Comment by zcbenz** [comment] 2020-05-09 06:46
Which operating system are you using?

**Comment by dimitrov-adrian** [comment] 2020-05-11 20:02
macOS 10.15
node: v12.16.3
gui: 0.8.1

**Comment by zcbenz** [comment] 2020-05-18 10:59
The `TextAttributes` is only used by `Painter.drawText` when drawing custom text, it does not apply to `Label` and `setStyle` can not be used to change the attributes of `Label`. So I'm closing this since it is not a bug.

However in the meanwhile I'm adding a new `AttributedText` API which would allow setting attributes for text in `Label`, so this will be possible soon.

**Closed by zcbenz** 2020-05-18 10:59 UTC
Labels: bug
